### ISSUE TITLE
Voice selection bug

### ISSUE THREAD

**Issue by Casartellii** [Language-Tools/anki-language-tools#83]
![anki_agRGW69Lju](https://user-images.githubusercontent.com/88219689/156075247-4c682e16-e2ab-4fd9-8723-53959a03c732.gif)

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.48 (fb07bad3) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-02-27 22:43:07

Caught exception:
Traceback (most recent call last):
  File "C:\Users\Casartelli\AppData\Roaming\Anki2\addons21\771677663\gui.py", line 34, in show_voice_selection
    dialog_voiceselection.voice_selection_dialog(languagetools, aqt.mw)
  File "C:\Users\Casartelli\AppData\Roaming\Anki2\addons21\771677663\dialog_voiceselection.py", line 248, in voice_selection_dialog
    voice_selection_dialog = prepare_voice_selection_dialog(languagetools, languagetools.voice_list)
AttributeError: 'LanguageTools' object has no attribute 'voice_list'

```

**Comment by luc-languagetools** [comment]
thank you for this bug report, let me look into it more closely. did you get an error message at startup about missing language data ?

**Comment by Casartellii** [comment]
"Could not load language data from the server, please try to restart Anki". That's the message I always get when starting Anki without an internet connection. I did some tests and found that if I launch Anki while having an internet connection, I don't get the message at startup and, as a result, don't get the error as well when attempting to change the voice.

**Comment by Casartellii** [comment]
I'm located in Brazil, and I use VPN software.
