### ISSUE TITLE
Please solve the proxy issue automatically by python code .

### ISSUE THREAD

**Issue by HillCat** [Language-Tools/anki-language-tools#84]
"When I double-click on the Anki icon, an error message pops up. I tried searching for the error on Google, but couldn’t find anything useful. I have copied and pasted the error message to the bottom of my post. **When I closed the proxy,the issue is off,when I open the proxy, the issue is come again.How to modify python code to solve the problem automatically**?

these are Error Message:
{
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you’ve discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-03-19 12:26:40

ERROR:root:could not load language data
Traceback (most recent call last):
File “C:\Users\47664\AppData\Roaming\Anki2\addons21\771677663\languagetools.py”, line 77, in initialize
self.language_data = self.cloud_language_tools.get_language_data()
File “C:\Users\47664\AppData\Roaming\Anki2\addons21\771677663\cloudlanguagetools.py”, line 17, in get_language_data
response = requests.get(self.base_url + ‘/language_data_v1’)
File “requests\api.py”, line 76, in get
File “requests\api.py”, line 61, in request
File “requests\sessions.py”, line 542, in request
File “requests\sessions.py”, line 655, in send
File “requests\adapters.py”, line 439, in send
File “urllib3\connectionpool.py”, line 696, in urlopen
File “urllib3\connectionpool.py”, line 964, in prepare_proxy
File “urllib3\connection.py”, line 359, in connect
File “urllib3\connection.py”, line 500, in connect_tls_proxy
File "urllib3\util\ssl.py", line 453, in ssl_wrap_socket
File "urllib3\util\ssl.py", line 495, in _ssl_wrap_socket_impl
File “ssl.py”, line 500, in wrap_socket
File “ssl.py”, line 997, in _create
ValueError: check_hostname requires server_hostname
}

**Comment by luc-languagetools** [comment]
Hi, can you provide more details about why you're using a proxy ? and do you know what kind of proxy it is ?
